### ISSUE TITLE
[Feature] Darters toevoegen aan een wedstrijd

### ISSUE THREAD

**Issue by tr4wzified** [RayBarneveldInc/Dartin#1]
**Beschrijving**
Er moeten darters kunnen worden toegevoegd aan wedstrijden.

**Reden**
We willen bijhouden welke darters er aan het spelen zijn.

**User Story**
Als gebruiker van de applicatie wil ik kunnen zien welke darters tegen elkaar aan het spelen zijn in een wedstrijd.

**Criteria / Definition of Done**
Wanneer het mogelijk is om darters op te halen van een gespecifieerde wedstrijd en deze te tonen aan de gebruiker, ook moeten deze darters door de wedstrijdleiding toegevoegd kunnen worden aan wedstrijden.

**Risico**
Gemiddeld

**MoSCoW-prioriteit**
Must-have

**Geschatte tijdsduur**
2 uur

**Aanvullende context & externe verwijzingen**
n.v.t

**Comment by MauricePonte** [comment]
Niet meer relevant, als test aangemaakt. Zie [Feature] Spelers kunnen aanmaken.
