### ISSUE TITLE
[Feature] Score van de wedstrijd bijhouden.

### ISSUE THREAD

**Issue by MauricePonte** [RayBarneveldInc/Dartin#12]
**Beschrijving**
Er moet functionaliteit gemaakt worden waarmee wedstrijd scores bijgehouden kunnen worden. 
Hiermee moet er per speler een beurt bijgehouden worden waarin maximaal drie worpen worden ingevoerd. 
Als een beurt volledig is ingevoerd moet de beurt automatisch naar de volgende speler gaan. 
Als een leg voltooid is moet er naar een volgende leg worden overgesprongen. 
Aanvankelijk van hoe de wedstrijd is ingericht, moet er nadat een speler een x aantal legs behaald heeft, een set worden toegereikt. 
Wanneer een speler de winnende aantal sets heeft bereikt moet er worden aangegeven hebben wie er heeft gewonnen. En een aantal opties om verder te gaan worden weergeven.
Er moet geen foutieve invoer geaccepteerd worden. 

**Reden**
Zie user stories

**User Story**

    1. Als gebruiker wil ik beurten voor dartwedstrijden kunnen toevoegen, zodat ik naam van de speler die de beurt speelt, op welk vak elke individuele pijl is gepland, toegekende eindscore kan bijhouden. 
    2. Als gebruiker wil ik dat voor beurten in dartwedstrijden niet elke pijl nodig is om een beurt af te maken, zodat ik de realistische gegevens voor beurten kan bijhouden. 
    3. Als gebruiker wil ik voor beurten afgeketste pijlen bijhouden, zodat ik een compleet beeld kan bewaren van een hele dartwedstrijd.  
    4. Als gebruiker wil ik dat scores van een beurt die te hoog zijn niet bijgeschreven worden, zodat de score correct bewaard blijft. 

**Criteria / Definition of Done**
Wanneer er per speler de score per beurt bijgehouden kan worden. Deze geen invalide invoer toestaat. 

**Risico**
Hoog
Als een wedstrijd niet kan worden bijgehouden kan de beoogde functionaliteit van de app niet behaald worden. 
Als verkeerde invoer word geaccepteerd word kan dit voor het niet correcte wedstrijd zorgen. 

**MoSCoW-prioriteit**
Must-have

**Geschatte tijdsduur**
40

**Aanvullende context & externe verwijzingen**
![image](https://user-images.githubusercontent.com/16573895/136843641-7d4754b7-94c5-4704-b7ad-264534c91718.png)
![image](https://user-images.githubusercontent.com/16573895/136843616-774085b2-4d4d-4545-982e-c410466c90d8.png)

**Comment by ork44** [comment]
@boele @Jaspervanderlugt
