### ISSUE TITLE
[Feature] Main menu van de applicatie

### ISSUE THREAD

**Issue by MauricePonte** [RayBarneveldInc/Dartin#16]
**Beschrijving**
Er moet een main menu worden gemaakt voor de applicatie

**Reden**
Zodat de gebruiker een overzichtelijk startpunt heeft voor het navigeren door de applicatie. 

**User Story**
n.v.t.

**Criteria / Definition of Done**
Wanneer er een overzichtelijke main menu in de UI van de applicatie is toegevoegd. 

**Risico**
Hoog
Zonder main menu is er geen duidelijk begin aan de applicatie. 

**MoSCoW-prioriteit**
Must-have

**Geschatte tijdsduur**
16

**Aanvullende context & externe verwijzingen**
MOCKUP TOEVOEGEN

**Comment by tr4wzified** [comment]
![Dartin-MainMenu](https://user-images.githubusercontent.com/55751269/135228813-9f66db34-c8cc-41b0-85ab-fb64a04a3dc6.png)
Eventueel concept

**Comment by MauricePonte** [comment]
Co-assignees: @Jacsquare
