### ISSUE TITLE
[Feature] Rapportages van wedstrijden aanmaken en inzien.

### ISSUE THREAD

**Issue by MauricePonte** [RayBarneveldInc/Dartin#17]
**Beschrijving**
Er moeten rapportages komen over wedstrijden. Waarin een scala aan gegevens over de wedstrijd in te lezen zijn. 
Gegevens die ten minste moeten worden toegevoegd: 
Zie screenshot in aanvullende info. 

**Reden**
Zie user stories. 

**User Story**
    1. Als gebruiker wil dat er rapportages worden opgeslagen per wedstrijd met daarin de deelnemende spelers, zodat ik weet welke spelers deelnamen aan een gegeven wedstrijd. 

    2. Als gebruiker wil dat er rapportages worden opgeslagen per wedstrijd met daarin de winnaar van de gegeven wedstrijd, zodat ik weet wie een bepaalde wedstrijd heeft gewonnen. 

    3. Als gebruiker wil dat er rapportages worden opgeslagen per wedstrijd met daarin de verliezer van de gegeven wedstrijd, zodat ik weet wie een bepaalde wedstrijd heeft verloren. 

    4. Als gebruiker wil dat er rapportages worden opgeslagen per wedstrijd met daarin de totaal gespeelde legs, zodat ik weet hoeveel legs er gespeeld zijn. 

    5. Als gebruiker wil dat er rapportages worden opgeslagen per wedstrijd met daarin de uitslag weergegeven in legs, zodat ik weet van een bepaalde wedstrijd in legs. 

**Criteria / Definition of Done**
Wanneer is deze functionaliteit afgemaakt en klaar om opgenomen te worden in het programma?

**Risico**
Laag
Rapportages in een must have. Bij het niet leveren van is de beoogde functionaliteit van de app niet behaald. 

**MoSCoW-prioriteit**
Must-have

**Geschatte tijdsduur**
24

**Aanvullende context & externe verwijzingen**
![afbeelding](https://user-images.githubusercontent.com/27705424/135057908-e65347d8-1bc9-4f02-a669-98a7b7b026b2.png)
VERDERE MOCKUPS TOEVOEGEN!

**Comment by Jacsquare** [comment]
![image](https://user-images.githubusercontent.com/43779942/135996287-1dea5b85-4d0d-4a58-9060-d890bbee81cd.png)
