### ISSUE TITLE
[Feature] Voeg unit test project toe

### ISSUE THREAD

**Issue by rodeknopje** [RayBarneveldInc/Dartin#25]
**Beschrijving**
Er moet een unit test project worden toegevoegd aan de solution

**Reden**
Om valideren of geschreven code doet wat we willen.

**User Story**
N.v.t

**Criteria / Definition of Done**
Als we kunnen unit testen doormiddel van het project

**Risico**
Laag

**MoSCoW-prioriteit**
Must-have

**Geschatte tijdsduur**
30 min

**Comment by MauricePonte** [comment]
Co-assignees: @JanSHoekstra
