### ISSUE TITLE
[Feature] Het opslaan & importeren van objecten in JSON-formaat

### ISSUE THREAD

**Issue by tr4wzified** [RayBarneveldInc/Dartin#3]
**Beschrijving**
Wedstrijden en de geschiedenis van eerder gespeelde wedstrijden moeten kunnen worden opgeslagen. Het globaal opslaan van objecten is daarom een must.

**Reden**
Het is een eis van de opdrachtgever, we kunnen niet onthouden welke wedstrijden er zijn gespeeld zonder deze op te slaan.

**User Story**
Als gebruiker wil ik de wedstrijdresultaten terug kunnen lezen zodat ik deze niet vergeet.

**Criteria / Definition of Done**
Wanneer de klasse naar een bestand kan worden geschreven en kan worden geïmporteerd.

**Risico**
Hoog. Wanneer het opslaan en importeren niet goed werkt kan de data corrupt raken.

**MoSCoW-prioriteit**
Must-have

**Geschatte tijdsduur**
2 uur

**Aanvullende context & externe verwijzingen**
n.v.t

**Comment by MauricePonte** [comment]
Co-assignees: @Jaspervanderlugt

**Comment by tr4wzified** [comment]
![Saving drawio(1)](https://user-images.githubusercontent.com/55751269/135244863-dd08de66-1d41-4298-ba7f-35f0ad316d5a.png)
[Saving.txt](https://github.com/RayBarneveldInc/Dartin/files/7250765/Saving.txt)

**Comment by tr4wzified** [comment]
![Saving drawio(3)](https://user-images.githubusercontent.com/55751269/135245588-a15b300b-84aa-495a-be4a-4c2e58032154.png)
