### ISSUE TITLE
[Feature] Resources in gescheiden bestand

### ISSUE THREAD

**Issue by Hoekstraa** [RayBarneveldInc/Dartin#4]
**Beschrijving**
Het gebruik van een xml of een dergelijk markup databestand voor het opslaan van statische, constante variabelen,
zoals tekst en standaard waarden.

**Reden**
Deze feature draagt bij aan de code schoon en overzichtelijk houden door constante waarden gezamenlijk te bewaren.

**User Story**
Als programmeur wil ik statische variabelen in een apart bestand kunnen zetten zodat constanten op 1 plek worden bewaard.

**Criteria / Definition of Done**
Een variabele in een xml bestand kan worden (her)gebruikt in de code, door middel van 1 lijn aan code.

**Risico**
laag

**MoSCoW-prioriteit**
Could-have

**Geschatte tijdsduur**
1 dag

**Aanvullende context & externe verwijzingen**
Waarschijnlijk geimplementeerd met zoiets dergelijks: https://docs.microsoft.com/en-us/dotnet/core/extensions/create-resource-files

**Comment by MauricePonte** [comment]
Co-assignees: @Jacsquare @Silentjeerd

**Comment by Hoekstraa** [comment]
Via keybinding/context-dependent strings naar resources sturen o.i.d.
